apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  labels:
    app: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: <your-docker-repo>/your-image-name:latest  # Replace with your Docker image
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"  # Adjust Java memory options as needed
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use ClusterIP if you don't want an external IP
