apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use ClusterIP if you don't want an external IP
