name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Build Docker image
      run: docker build -t your-docker-repo/your-image-name:${{ github.sha }} .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to ECR
      run: |
        docker tag your-docker-repo/your-image-name:${{ github.sha }} <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:${{ github.sha }}
        docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl rollout status deployment/user-app-deployment
